version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: pipeline-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      - pipnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: myapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_HOST: pipeline-db
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: root
      DB_PASS: root
    networks:
      - pipnet

networks:
  pipnet: