pipeline {
    agent any

    environment {
        KUBECONFIG = "C:\\Users\\shubh\\.kube\\config"
    }

    stages {
        stage('Checkout') {
             steps {
                git branch: 'main', url: 'https://github.com/Shubh-Namdev/pipeline.git'
            }
        }

        stage('Deploy to Minikube') {
            steps {
                echo 'Applying Kubernetes manifests...'
                bat 'kubectl apply -f k8s/cloud-storage/'
                //bat 'kubectl apply -f service.yaml'
            }
        }

        stage('Verify Deployment') {
            steps {
                echo 'Checking pods and services...'
                bat 'kubectl get pods'
                bat 'kubectl get svc'
            }
        }
    }
}