// CI Pipeline
pipeline{
    agent any

    environment {
        //DOCKER_IMAGE = "shubhamnamdev01/springboot-mysql-k8s${env.BUILD_NUMBER}"
        DOCKER_IMAGE = "shubhamnamdev01/k8s-pipeline:v1"

    }

    tools {
        gradle 'Gradle 8.14.2'
        jdk 'JDK21'
    }


    stages{
        stage("Checkout"){
            steps {
                git branch: 'main', url: 'https://github.com/Shubh-Namdev/pipeline.git'
            }
            post{
                success{
                    echo 'successfully fetched the repo'
                }
                failure{
                    echo 'failed to fetch the repository'
                }
            }
        }

        stage("Build"){
            steps {
                sh '''
                  chmod +x gradlew
                  ./gradlew clean build -x test
                '''
            }
            post{
                success{
                    echo 'build successfull'
                }
                failure{
                    echo 'build failed'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-reg-cred', usernameVariable: 'REG_USER', passwordVariable: 'REG_PASS')]) {
                    sh 'echo $REG_PASS | docker login -u $REG_USER --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

    }
    post{
        always{
           cleanWs()
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}